version: "3"

networks:
    microblog: 
      ipam:
        driver: default
        config:
          - subnet: 172.28.0.0/16

services:
    db:
        image:   mysql/mysql-server:5.7
        container_name: "microblog-database"
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=dbpass
        restart:
            "always"
        expose:
          - "3306"
        networks:
          microblog:
    prod:
        build: 
          dockerfile: docker/Dockerfile-prod
          context: .
        container_name: "microblog-production"
        links:
          - "db:microblog-database"
        ports:
            - 8000:5000
        environment:
            - SECRET_KEY=production
            - DATABASE_URL=mysql+pymysql://microblog:dbpass@microblog-database:3306/microblog
        restart:
            "always"
        networks:
          microblog:
    test:
        build: 
          dockerfile: docker/Dockerfile-test
          context: .
        container_name: "microblog-test"
        volumes: 
          - ".:/home/microblog/microblog"
        ports:
            - 8000:5000
        environment:
            - SECRET_KEY=test
        restart:
            "always"
        networks:
          microblog:


