---
    - name: "Launch docker container with microblog application"
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image }}"
        restart_policy: always
        network_mode: host
        env:
          SECRET_KEY: "{{ secret_key }}"
          DATABASE_URL: "{{ database_url }}"

    - name: "Fetch image for statsd exporter gunicorn"
      command:
         docker pull prom/statsd-exporter

    - name: Create statds config
      template:
        src: ./templates/gunicorn.conf.j2
        dest: ~/statds.conf
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'

    - name: Launch statsd exporter for gunicorn
      command:
         docker run -dP --net=host -v ${PWD}/statsd.conf:/statsd/statsd.conf prom/statsd-exporter "--statsd.mapping-config=/statsd/statsd.conf"
