---
  # Node Exporter
    - name: create project directory downloads
        file: state=directory path=/etc/node_exporter

    - name: Download node_exporter file
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: .
        mode: '0440'

    - name: Extract downloaded node_exporter file
      unarchive:
        src: xvzf node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /etc/node_exporter

    - name: Add user to node_exporter
      command: sudo useradd -rs /bin/false node_exporter
    
    - name: Copy file with owner and permissions
      copy:
        src: /etc/node_exporter/node_exporter-0.18.1.linux-amd64/node_exporter
        dest: /usr/local/bin
        owner: node_exporter
        group: node_exporter

    - name: Change in the file of prometheus.yml
      template:
        src: ./templates/node_exporter_template.j2
        dest: /etc/systemd/systemd/node_exporter.service
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'
    
    - name: Reload daemon
      command: sudo systemctl daemon-reload
    
    - name: Start node_exporter
      command: sudo systemctl start node_exporter
    
    - name: Curl to see node_exporter
      command: curl http://localhost:9100/metrics

  # Installing Prometheus
    - name: create project directory downloads
        file: state=directory path=/etc/prometheus

    - name: Download prometheus file
        get_url:
          url: https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz
          dest: .
          mode: '0440'

    - name: Extract downloaded prometheus file
      unarchive:
        src: prometheus-2.10.0.linux-amd64.tar.gz
        dest: /etc/prometheus
    
    - name: Enter prometheus downloaded file
      command: cd prometheus-2.10.0.linux-amd64/

    - name: Change in the file of prometheus.yml
      template:
        src: ./templates/prometheus_template.j2
        dest: prometheus-2.10.0.linux-amd64/prometheus.yml
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'
    
    - name: Launch prometheus as a background process
      command: ./prometheus &


    # Installing Graphana
    - name: create project directory downloads
        file: state=directory path=/etc/graphana

    - name: Download graphana files
        get_url:
          url: https://dl.grafana.com/oss/release/grafana_6.2.4_amd64.deb
          dest: .
          mode: '0440'

    - name: Extract the graphana files
      command: sudo dpkg -i grafana_6.2.4_amd64.deb
    