---
    apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-secrets
    type: Opaque
    data:
      ROOT_PASSWORD: bGFzdC1wYXNzd29yZC1ldmVyLXRvLWV4aXN0
      DB_PASSWORD: bWljcm9zcGFzc3c=