---
    - name: create project directory downloads
        file: state=directory path=/etc/prometheus

    - name: Download prometheus file
        get_url:
          url: https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz
          dest: /etc/prometheus
          mode: '0440'

    - name: Extract downloaded prometheus file
      unarchive:
        src: prometheus-2.10.0.linux-amd64.tar.gz
        dest: /etc/prometheus
    
    - name: Enter prometheus downloaded file
      command: cd prometheus-2.10.0.linux-amd64/

    - name: Change in the file of prometheus.yml
      template:
        src: ./templates/prometheus_template.j2
        dest: prometheus-2.10.0.linux-amd64/prometheus.yml
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'
    
    - name: Launch prometheus as a background process
      command: ./prometheus & 