version: "3"
services: 
    db:
        image:   mysql/mysql-server:5.7
        container_name: "microblog-database"
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=dbpass
        restart:
            "always"
        ports:
          - 3306:3306